/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SubmitPage = {
  _id: string;
  _type: "submitPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  formUrl?: string;
  blurb?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  strap?: string;
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  headline: string;
  slug: Slug;
  showName: string;
  startDate?: string;
  endDate?: string;
  showUrl?: string;
  tagline?: string;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
  };
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishedAt: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SubmitPage
  | SanityImageAssetReference
  | AboutPage
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | Review
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries.ts
// Variable: REVIEWS_PAGE_QUERY
// Query: *[_type == "review" && !(_id in path("drafts.**"))] | order(publishedAt desc) [$start...$end] {      "slug": slug.current,  headline,  showName,  startDate,  endDate,  showUrl,  tagline,  body,  publishedAt,  heroImage {    alt,    caption,    asset->{      url,      "dimensions": metadata.dimensions    }  }  }
export type REVIEWS_PAGE_QUERY_RESULT = Array<{
  slug: string;
  headline: string;
  showName: string;
  startDate: string | null;
  endDate: string | null;
  showUrl: string | null;
  tagline: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishedAt: string;
  heroImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      url: string;
      dimensions: SanityImageDimensions | null;
    } | null;
  };
}>;

// Source: sanity/queries.ts
// Variable: REVIEW_BY_SLUG_QUERY
// Query: *[_type == "review" && slug.current == $slug && !(_id in path("drafts.**"))][0] {      "slug": slug.current,  headline,  showName,  startDate,  endDate,  showUrl,  tagline,  body,  publishedAt,  heroImage {    alt,    caption,    asset->{      url,      "dimensions": metadata.dimensions    }  }  }
export type REVIEW_BY_SLUG_QUERY_RESULT = {
  slug: string;
  headline: string;
  showName: string;
  startDate: string | null;
  endDate: string | null;
  showUrl: string | null;
  tagline: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  publishedAt: string;
  heroImage: {
    alt: string | null;
    caption: string | null;
    asset: {
      url: string;
      dimensions: SanityImageDimensions | null;
    } | null;
  };
} | null;

// Source: sanity/queries.ts
// Variable: REVIEW_SLUGS_QUERY
// Query: *[_type == "review" && !(_id in path("drafts.**"))] | order(publishedAt desc) [0...$limit] {    "slug": slug.current  }
export type REVIEW_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/queries.ts
// Variable: ARCHIVE_PAGE_QUERY
// Query: *[_type == "review" && !(_id in path("drafts.**"))] | order(publishedAt desc) [$start...$end] {      "slug": slug.current,  headline,  showName,  tagline,  startDate,  endDate,  "imageUrl": heroImage.asset->url  }
export type ARCHIVE_PAGE_QUERY_RESULT = Array<{
  slug: string;
  headline: string;
  showName: string;
  tagline: string | null;
  startDate: string | null;
  endDate: string | null;
  imageUrl: string | null;
}>;

// Source: sanity/queries.ts
// Variable: ARCHIVE_SEARCH_QUERY
// Query: *[_type == "review" && !(_id in path("drafts.**")) && (    headline match $q || showName match $q || pt::text(body) match $q  )] | order(publishedAt desc) [0...$limit] {      "slug": slug.current,  headline,  showName,  tagline,  startDate,  endDate,  "imageUrl": heroImage.asset->url  }
export type ARCHIVE_SEARCH_QUERY_RESULT = Array<{
  slug: string;
  headline: string;
  showName: string;
  tagline: string | null;
  startDate: string | null;
  endDate: string | null;
  imageUrl: string | null;
}>;

// Source: sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] { strap }
export type SITE_SETTINGS_QUERY_RESULT = {
  strap: string | null;
} | null;

// Source: sanity/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0] {    title,    body,    image {      alt,      asset->{ url, "dimensions": metadata.dimensions }    }  }
export type ABOUT_QUERY_RESULT = {
  title: string | null;
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    alt: string | null;
    asset: {
      url: string;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries.ts
// Variable: SUBMIT_QUERY
// Query: *[_type == "submitPage" && _id == "submitPage"][0] { body, formUrl, blurb }
export type SUBMIT_QUERY_RESULT = {
  body: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  formUrl: string | null;
  blurb: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "review" && !(_id in path("drafts.**"))] | order(publishedAt desc) [$start...$end] {\n    \n  "slug": slug.current,\n  headline,\n  showName,\n  startDate,\n  endDate,\n  showUrl,\n  tagline,\n  body,\n  publishedAt,\n  heroImage {\n    alt,\n    caption,\n    asset->{\n      url,\n      "dimensions": metadata.dimensions\n    }\n  }\n\n  }\n': REVIEWS_PAGE_QUERY_RESULT;
    '\n  *[_type == "review" && slug.current == $slug && !(_id in path("drafts.**"))][0] {\n    \n  "slug": slug.current,\n  headline,\n  showName,\n  startDate,\n  endDate,\n  showUrl,\n  tagline,\n  body,\n  publishedAt,\n  heroImage {\n    alt,\n    caption,\n    asset->{\n      url,\n      "dimensions": metadata.dimensions\n    }\n  }\n\n  }\n': REVIEW_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "review" && !(_id in path("drafts.**"))] | order(publishedAt desc) [0...$limit] {\n    "slug": slug.current\n  }\n': REVIEW_SLUGS_QUERY_RESULT;
    '\n  *[_type == "review" && !(_id in path("drafts.**"))] | order(publishedAt desc) [$start...$end] {\n    \n  "slug": slug.current,\n  headline,\n  showName,\n  tagline,\n  startDate,\n  endDate,\n  "imageUrl": heroImage.asset->url\n\n  }\n': ARCHIVE_PAGE_QUERY_RESULT;
    '\n  *[_type == "review" && !(_id in path("drafts.**")) && (\n    headline match $q || showName match $q || pt::text(body) match $q\n  )] | order(publishedAt desc) [0...$limit] {\n    \n  "slug": slug.current,\n  headline,\n  showName,\n  tagline,\n  startDate,\n  endDate,\n  "imageUrl": heroImage.asset->url\n\n  }\n': ARCHIVE_SEARCH_QUERY_RESULT;
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] { strap }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0] {\n    title,\n    body,\n    image {\n      alt,\n      asset->{ url, "dimensions": metadata.dimensions }\n    }\n  }\n': ABOUT_QUERY_RESULT;
    '\n  *[_type == "submitPage" && _id == "submitPage"][0] { body, formUrl, blurb }\n': SUBMIT_QUERY_RESULT;
  }
}
