import { cache } from "react";
import type { PortableTextBlock } from "@portabletext/types";
import type {
  SITE_SETTINGS_QUERY_RESULT,
  ABOUT_QUERY_RESULT,
  SUBMIT_QUERY_RESULT,
} from "@/sanity.types";
import { SITE_SETTINGS_QUERY, ABOUT_QUERY, SUBMIT_QUERY } from "@/sanity/queries";
import {
  strap as DEFAULT_STRAP,
  aboutStatement,
  SUBMIT_FORM_URL,
} from "@/content/site";
import { sanityFetch } from "./sanity-fetch";
import {
  aboutBodyBlocks,
  submitBodyBlocks,
  submitBlurbBlocks,
} from "./copy-blocks";
import { aboutImage, type AboutImage } from "./about-image";

// The site's editable copy comes from Sanity singletons, with content/site.ts
// as the committed fallback. Every field falls back independently, so a
// singleton that exists but is missing one field still renders — nothing can
// come out blank. Before Bryan seeds/edits anything, the site looks exactly as
// it does today, because the fallback IS today's copy.
//
// Fetching goes through sanityFetch, tagged "copy" so /api/revalidate flushes it
// on publish. The row types below are loose on purpose — the str()/blocks()
// coalescers accept unknown and fall back per field.

const str = (v: unknown, fallback: string): string =>
  typeof v === "string" && v.trim() ? v : fallback;

const blocks = (v: unknown, fallback: PortableTextBlock[]): PortableTextBlock[] =>
  Array.isArray(v) && v.length ? (v as PortableTextBlock[]) : fallback;

export type AboutContent = {
  title: string;
  body: PortableTextBlock[];
  image: AboutImage | null;
};
export type SubmitContent = {
  body: PortableTextBlock[];
  formUrl: string;
  blurb: PortableTextBlock[];
};

export const getStrap = cache(async (): Promise<string> => {
  const row = await sanityFetch<{ strap: unknown } | null>(SITE_SETTINGS_QUERY, {}, "copy");
  return str(row?.strap, DEFAULT_STRAP);
});

export const getAboutContent = cache(async (): Promise<AboutContent> => {
  const row = await sanityFetch<{ title: unknown; body: unknown; image: unknown } | null>(
    ABOUT_QUERY,
    {},
    "copy",
  );
  return {
    title: str(row?.title, aboutStatement.title),
    body: blocks(row?.body, aboutBodyBlocks()),
    image: aboutImage(row?.image),
  };
});

export const getSubmitContent = cache(async (): Promise<SubmitContent> => {
  const row = await sanityFetch<{ body: unknown; formUrl: unknown; blurb: unknown } | null>(
    SUBMIT_QUERY,
    {},
    "copy",
  );
  return {
    body: blocks(row?.body, submitBodyBlocks()),
    formUrl: str(row?.formUrl, SUBMIT_FORM_URL),
    blurb: blocks(row?.blurb, submitBlurbBlocks()),
  };
});

// Compile-time binding: the copy projections must keep providing the fields the
// getters read (see the same pattern in map-review). Rename or drop `strap`,
// `title`, `formUrl`, etc. in a query and this stops compiling. sanity.types.ts
// is generated by `npm run typegen`.
type Assert<T extends true> = T;
type _StrapBinding = Assert<
  NonNullable<SITE_SETTINGS_QUERY_RESULT> extends { strap: unknown } ? true : false
>;
type _AboutBinding = Assert<
  NonNullable<ABOUT_QUERY_RESULT> extends { title: unknown; body: unknown; image: unknown }
    ? true
    : false
>;
type _SubmitBinding = Assert<
  NonNullable<SUBMIT_QUERY_RESULT> extends { body: unknown; formUrl: unknown; blurb: unknown }
    ? true
    : false
>;
